# Generated by Django 4.0.1 on 2022-02-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sucursal', models.CharField(max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=13)),
                ('estado', models.CharField(max_length=50)),
                ('codigo_postal', models.CharField(blank=True, max_length=5)),
                ('latitud', models.FloatField(blank=True)),
                ('longitud', models.FloatField(blank=True)),
                ('imagen', models.ImageField(blank=True, upload_to='imagenesSucursal')),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurante',
        ),
    ]
