# Generated by Django 4.0.1 on 2022-02-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_delete_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(max_length=100),
        ),
    ]
